apiVersion: v1
kind: Service
metadata:
  name: api-service-products
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: spring-port
  selector:
    app: api-products
